-- V3 isolated knowledge store.
-- V1/V2 tables are intentionally untouched. V3 ingestion writes only here.
create extension if not exists vector;

create table if not exists public.documents_gemini_v3 (
  id bigint generated by default as identity primary key,
  content text not null,
  embedding vector(3072) not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists documents_gemini_v3_metadata_gin
  on public.documents_gemini_v3 using gin (metadata);

create index if not exists documents_gemini_v3_source_path_idx
  on public.documents_gemini_v3 ((metadata->>'source_path'));

create index if not exists documents_gemini_v3_kb_version_idx
  on public.documents_gemini_v3 ((metadata->>'kb_version'));

-- V3 retrieval can add its own RPC/index strategy later. This first PR is
-- deliberately ingestion/storage only.
